server:
  port: 8087

spring:
  application:
    name: playground-backend
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/playground
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: playground-realm
  resource: ${spring.application.name}
  public-client: true
  principal-attribute: preferred_username
